### PR TITLE
catification step 2, code copy and yaml

### PR DESCRIPTION
**Pull request by hypergamer80**
copied original code, plus adaptations with yaml

### CODE REVIEW

**Comment by hypergamer80** [comment]
i named it catify,py- how dumb lol, changed it

**Comment by Kronifer** [comment]
Did you update pyproject.toml and lock for new reps?

**Comment by hypergamer80** [comment]
i'm not entirely sure how to do that

**Comment by Kronifer** [comment]
Oh nvm you're fine

**Review by Kronifer — APPROVED** [review]
lgtm

**Review by ShakyaMajumdar — APPROVED** [review]
lgtm

**Pull request merged**
