### PR TITLE
Catification: Negative Replies

### PR DESCRIPTION
**Pull request by Objectivitix**
implemented negative replies in constants.py, and implemented them in catify.py, replacing the placeholders.

### CODE REVIEW

**Comment by dawnofmidnight** [comment]
Can we wait till #22 is finished, so that we can be consistent?

**Comment by dannynotsmart** [comment]
everything looks ok

**Comment by hypergamer80** [comment]
alright, we'll wait.

**Comment by hypergamer80** [comment]
reverted previous changes

**Review by Kronifer — APPROVED** [review]
Lgtm

**Comment by Kronifer** [comment]
Before any approval is made, did you test the bot?

**Comment by Objectivitix** [comment]
you just saw me test it lmao

**Review by dannynotsmart — APPROVED** [review]
everything looks fine

**Comment by Objectivitix** [comment]
m e r g e d.

**Pull request merged**
