### PR TITLE
Add contributing guide

### PR DESCRIPTION
**Pull request by ShakyaMajumdar**
(ignore the first 4 commits its showing, idk why they're there lol)

### CODE REVIEW

**Review by Kronifer — APPROVED** [review]
Very, very clean, thanks!

**Review by Kronifer — CHANGES_REQUESTED** [review]
You mentioned black, add it to the pyproject.toml under Dev packages

**Review by Kronifer — APPROVED** [review]
Lgtm

**Comment by Objectivitix** [comment]
merged.

**Pull request merged**
