### PR TITLE
featured: docker, postgres, and taskipy

### PR DESCRIPTION
**Pull request by dawnofmidnight**
The bot can be a little bit hard to set up at the moment, and it uses JSON as a database, which we all know is bad practice. This PR dockerizes it all and sets up a postgres docker image to allow new changes.

### CODE REVIEW

**Comment by dawnofmidnight** [comment]
Don't merge this yet please, I need to set up taskipy.

**Comment by dawnofmidnight** [comment]
[`taskipy`](https://github.com/illBeRoy/taskipy) is now set up so that we can use the following commands:

```bash
poetry run task start  # to start the bot
poetry run task lint   # to invoke flake8
poetry run task format # to invoke black

**Review by AbooMinister25 — APPROVED** [review]
Everything looks good

**Comment by dawnofmidnight** [comment]
The status embed doesn't seem to be working, so I'll force merge since it technically meets all requirements.

**Pull request merged**
