### PR TITLE
Deleted pycache

### PR DESCRIPTION
**Pull request by Kronifer**
Pycache is taking up space, and it's unneeded. Let's tell pycache to fuck off

### CODE REVIEW

**Comment by ShakyaMajumdar** [comment]
There's a `__pycache__` in `bot/utilities` too

**Comment by Kronifer** [comment]
Lemme jus go kill it quick

**Comment by ShakyaMajumdar** [comment]
While we're removing unnecessary files, remove the `.replit` too

**Comment by Kronifer** [comment]
Kay

**Comment by hypergamer80** [comment]
yes, fk pycache

**Comment by ShakyaMajumdar** [comment]
LGTM

**Comment by Kronifer** [comment]
Y'all have the power of approval

**Review by ShakyaMajumdar — APPROVED** [review]

**Comment by Kronifer** [comment]
@hypergamer80 can you approve?

**Review by dawnofmidnight — APPROVED** [review]

**Pull request merged**
