### PR TITLE
Added action_embeds

### PR DESCRIPTION
**Pull request by Kronifer**
Added a workflow that makes nicer github actions embeds

### CODE REVIEW

**Review by Objectivitix — COMMENTED** [review]
uh here's the thing i don't really have that much experience with github internal shit so i can't approve nor disapprove. find someone else lol

**Comment by Kronifer** [comment]
Merging

**Comment by Objectivitix** [comment]
wha- you didn't get two approvals yet

**Comment by Kronifer** [comment]
Lol me admin

**Comment by Objectivitix** [comment]
discord administrators are only administrators so they can access and change certain information for other developpers' benefits such as an id of a certain role, tweaking channel overrides to fix a bug, manage server etc, and not to lead the group.

**Comment by Kronifer** [comment]
Lol I was joking

**Pull request merged**
