### PR TITLE
Rename fun.py to eval.py

### PR DESCRIPTION
**Pull request by Objectivitix**
per squid's request, rename this for less ambiguity

### CODE REVIEW

**Comment by Objectivitix** [comment]
virdan has taken over

**Comment by VirdanTheBurden** [comment]
:3

**Comment by Kronifer** [comment]
Closed, fun.py will contain `--duck`, I'm considering moving catify in there as well

**Comment by Objectivitix** [comment]
yes, colon 3 indeed.

**Comment by Objectivitix** [comment]
oop-

**Pull request closed without merging**
