### PR TITLE
added cats, step 1 of catification

### PR DESCRIPTION
**Pull request by hypergamer80**
i added all cats in the config.yaml file as a list form

### CODE REVIEW

**Review by Kronifer — APPROVED** [review]
lgtm

**Comment by hypergamer80** [comment]
little vote: which one do you guys think is more readable

A. full form
```yaml
cats:
  - "ᓚᘏᗢ"
  - "ᘡᘏᗢ"
  - "🐈"
  - "ᓕᘏᗢ"
  - "ᓇᘏᗢ"
  - "ᓂᘏᗢ"
  - "ᘣᘏᗢ"
  - "ᕦᘏᗢ"
  - "ᕂᘏᗢ"
```

B. compact form
```yaml
cats: ["ᓚᘏᗢ", "ᘡᘏᗢ", "🐈", "ᓕᘏᗢ", "ᓇᘏᗢ", "ᓂᘏᗢ", "ᘣᘏᗢ", "ᕦᘏᗢ", "ᕂᘏᗢ"]
```

**Comment by hypergamer80** [comment]
I quote Squid: "the whole point of yaml is to be human-readable, keep it"

so no compact form. A is better.

**Review by VirdanTheBurden — APPROVED** [review]
looks good, keep it like that ;3

**Pull request merged**
