### PR TITLE
when unmute, delete the id/time entry in json file

### PR DESCRIPTION
**Pull request by Objectivitix**
also added logical spacing and made it so that when the user doesn't have muted role it rejects

### CODE REVIEW

**Comment by Objectivitix** [comment]
WHAT TF IS WRONG WITH THIS LINT CHECK?! I-

**Comment by Kronifer** [comment]
Run black before committing, not approving until lint passes

**Comment by Objectivitix** [comment]
uh- i just ran black on it and guess what? the file did not change-

**Comment by Objectivitix** [comment]
lemme check again, it could be trailing whitespace

**Comment by Objectivitix** [comment]
oh wow- i shouldn't have questioned lint, it's working amazingly

apparently i can't even get one character off- very strict

**Review by Kronifer — APPROVED** [review]
lgtm

**Comment by Kronifer** [comment]
Merged due to being an error in mod systems

**Pull request merged**
