### PR TITLE
make zencat.py support turning pages

### PR DESCRIPTION
**Pull request by Objectivitix**

### CODE REVIEW

**Comment by Objectivitix** [comment]
this lint crap doesn't even work, i linted my code with black and here it says lint failed?? what??

**Comment by Kronifer** [comment]
Youre missing a black line at end of file

**Comment by Kronifer** [comment]
@Objectivitix ensure that you have one blank line at the end of your file

**Comment by Objectivitix** [comment]
why tf is there a conflict?!

**Comment by Kronifer** [comment]
Conflict fixed

**Review by Kronifer — APPROVED** [review]
Lgtm

**Review by dannynotsmart — APPROVED** [review]
code looks line 2 me

**Pull request merged**
