### PR TITLE
Added Bancmd

### PR DESCRIPTION
**Pull request by Kronifer**
Added the bancmd command, as well as redoing some code in bot.py so extensions load from subfolders

### CODE REVIEW

**Review by AbooMinister25 — APPROVED** [review]
Alright, so everything looks good, but in the future, maybe lets use embeds for error messages instead of just sending it in the channel.

**Comment by Kronifer** [comment]
@AbooMinister25 ill do some spring cleaning later

**Comment by AbooMinister25** [comment]
> @AbooMinister25 ill do some spring cleaning later

Alright

**Comment by dannynotsmart** [comment]
i like it

**Comment by Kronifer** [comment]
Alright then, ill approve and merge then

**Review by dannynotsmart — APPROVED** [review]
i like it super good, since we're fancy consider discord embeds. other than that i will approve it

**Comment by Kronifer** [comment]
@dannynotsmart sexy embeds will be added later

**Pull request merged**
