### PR TITLE
Added `--help` command

### LINKED ISSUE #46: Make a non shitty help command
We are currently using the default discord.py help command. Let's not! I propose we make a custom help command similar to the vanilla one, but we get help on commands based on the folder they're in, i.e utilities, moderation, fun, etc.

### PR DESCRIPTION
**Pull request by Kronifer**
Closes #46 

`--help` on its own returns a list of commands, but `--help [command or alias]` returns help on that command.

### CODE REVIEW

**Review by Objectivitix — CHANGES_REQUESTED** [review]
everything looks super good, except for the spacing in `help.py`. mind adding some logical newlines here and there so it's easier on the eyes? remember:

"Sparse is better than dense." -- TZOP, Line 5

**Comment by Kronifer** [comment]
@Objectivix what spacing are you talking about? Be specific

**Review by Objectivitix — APPROVED** [review]
looks soooooo much better. approved :D

**Comment by Kronifer** [comment]
POG

**Review by AbooMinister25 — APPROVED** [review]
Alright, I've looked this over, and everything seems great.

**Pull request merged**
