### PR TITLE
add cats to constants.py

### PR DESCRIPTION
**Pull request by hypergamer80**
this is the first step. next step is to copy catify code.

### CODE REVIEW

**Review by Kronifer — CHANGES_REQUESTED** [review]
Move cars to config.yml and get them from there

**Comment by hypergamer80** [comment]
so if i'm doing that i'm closing this pr, and opening a real one.

**Comment by dawnofmidnight** [comment]
No need to open extra prs. You can simply revert this one and add it.

**Comment by hypergamer80** [comment]
i already opened an extra, i'm not that familar with github. it's alright, it's just one extra pr, not like that's gonna fk up all the code

**Pull request closed without merging**
