### PR TITLE
i fucked up indents, smh

### PR DESCRIPTION
**Pull request by Objectivitix**
please approve, urgent bug fix

### CODE REVIEW

**Review by Kronifer — APPROVED** [review]
What in the fuck did you even- I'm not even gonna ask

**Comment by Objectivitix** [comment]
did i lint? no, since i made sure manually everything was pep8ified.

**Comment by Objectivitix** [comment]
but it seems as if "manually" is very bad practice-

**Comment by Objectivitix** [comment]
speaking of which, how do i lint??

**Comment by Kronifer** [comment]
Use black, it's added as a dev package with poetry

**Comment by Objectivitix** [comment]
is there a button that i press?

**Comment by Kronifer** [comment]
In terminal, do poetry install and then do poetry run black

**Review by dannynotsmart — APPROVED** [review]
good
bien
好

**Comment by Kronifer** [comment]
Fuckin merged

**Pull request merged**
