### PR TITLE
Set up base file structure.

### LINKED ISSUE #2: Start the bot
Add some basic cog structuring, stuff like that

### PR DESCRIPTION
**Pull request by dannynotsmart**
Closes #2.

This pr will set up the file structure for the bot and make it possible to add cogs easily.

*Edited by dawnofmidnight*

### CODE REVIEW

**Comment by Kronifer** [comment]
It looks good, but we need to figure out hosting first

**Comment by dawnofmidnight** [comment]
Shouldn't it be `__main__.py`?

**Comment by dannynotsmart** [comment]
IDK HOW GITHUB WORKS FORGIVE MEE

**Review by Kronifer — CHANGES_REQUESTED** [review]
Maybe make a folder called bot and move this into it as __main__.py

**Comment by dawnofmidnight** [comment]
It's fine. But let's do what kronifer said and add the base of the whole bot in one pr instead of 50

**Comment by Kronifer** [comment]
Agreed

**Comment by dawnofmidnight** [comment]
I'm closing this, because #5 sets up the basics

**Pull request closed without merging**
