### PR TITLE
Add duration modifier to bans.py/mute cmd

### PR DESCRIPTION
**Pull request by Objectivitix**
Using a DURATION_DICT in constants.py, I implemented a duration setting into the mute command's asyncio timer.

ex. `!mute @yeet 3h reason blah blah` would mute user yeet for 3 hours.

### CODE REVIEW

**Comment by Objectivitix** [comment]
i also added spacing.

**Comment by dannynotsmart** [comment]
A big issue.
I like the idea of adding durations, however;
I do not think it is a good choice to use asyncio.sleep() for the duration. This is simply because if the bot closes, or goes into manufacturing, this process will be lost. They will never be automatically unbanned/unmuted

My solution is this:
Simply save the Epoch time of when the unban/unmute occurs. Use an task loop, check if the current epoch time is greater than the saved epoch times. If it is, unmute.
Lmk if theres any other alternatives (i heard about a scheduling module as well)

**Comment by dannynotsmart** [comment]
when you save the epoch thing, maybe save it in an json file

**Comment by Objectivitix** [comment]
true. i believe @Kronifer was the one who implemented this first, i simply went with the same approach of asyncio.

there is this one time where i spent 4 hours studying the datetime module just because i was bored

i believe that knowledge will come in very handy now @dannynotsmart ;)

**Comment by Objectivitix** [comment]
TWO FKING HOURS OF DEBUGGING MATE

FINALLY FIXED LIKE, 50 BUGS

MY BRAIN IS FRIED. FRIIIIEIEEIEIED.

there are some dependencies i would like to get rid of, but im done today. those are for tmr

**Comment by Objectivitix** [comment]
i will update the code tmr, to the no-bug version

**Comment by Kronifer** [comment]
No rush

**Comment by Objectivitix** [comment]
LESSSSSSSSSSSSSSSSGO TESTING WORKED

**Comment by Objectivitix** [comment]
not sure about that yaml getter func tho, if it bugs out we'll have to see what the problem is

**Comment by Objectivitix** [comment]
i also did a complete update on the mute cmd lol

**Review by Kronifer — APPROVED** [review]
Pretty poggers

**Comment by Kronifer** [comment]
> Using a DURATION_DICT in constants.py, I implemented a duration setting into the mute command's asyncio timer.
> 
> ex. `!mute @yeet 3h reason blah blah` would mute user yeet for 3 hours.

Maybe I should deny, you muted me lol

**Comment by Objectivitix** [comment]
@Kronifer you're yeet | cat, not yeet xD

**Review by AbooMinister25 — APPROVED** [review]
Everything looks good, and seems to work correctly.

**Comment by Objectivitix** [comment]
mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmerged.

**Pull request merged**
