### PR TITLE
made bot send dm to person getting infracted.

### LINKED ISSUE #66: [feature] Send dm to the user that gets infracted.
**What is the feature you want to add?**
Whenever a user gets an infraction like a ban or a mute, a DM embed can be sent by the bot to the person who got infracted highlighting some useful information.

**Describe the solution you'd like**
An embed sent to the infracted user containing information. The one below is just an example
image
This needn't be the case, more Info like, infraction type, reason for infraction, infraction until what time period, and a link to the server rules (like the example of python discord) can be specified. 

**Describe alternatives you've considered**
I've considered no alternatives but my proposed solution hopefully would do the job just fine. In my opinion something like this is really necessary since I got muted before for spamming embeds but I had no idea why I got muted until I checked the mod logs which not everyone has access to. 

**Would you like to implement this?**
yes!

### PR DESCRIPTION
**Pull request by AnkithAbhayan**
Closes #66 
This PR makes the bot send a dm embed to the person getting infracted. I've only added this functionality to the Mute and Ban commands (should this be inculcated to the unmute command too? something like a "you have now been unmuted" ?) 

After looking at the code, you might be wondering as to why I made changes to the end of the mute function and similarly to the beginning of the ban function. This is because, the bot and the user has to be in a common server for dms to work. If I try to make the bot send a dm AFTER the person gets banned, I'm assuming that there will be an error since the person isn't in the server anymore.
```
Ankith
```

### CODE REVIEW

**Comment by AnkithAbhayan** [comment]
moment of truth...

**Comment by AnkithAbhayan** [comment]
Btw what're your thoughts on making the bot send dm when a person gets UNmuted?

**Comment by Kronifer** [comment]
Yeah that's good

**Review by Kronifer — APPROVED** [review]
Lgtm, thanks

**Review by Objectivitix — APPROVED** [review]
amazing, lgtm!!

**Pull request merged**
