### PR TITLE
Add config.yml

### LINKED ISSUE #6: Use yaml for config
For the sake of simplicity, we should use yaml for configuration. This would allow us to easily change values without much effort. We will use [pyyaml](https://pypi.org/project/PyYAML/) to parse.

### PR DESCRIPTION
**Pull request by dawnofmidnight**
Closes #6.

This pr adds a config.yml file. We can pull from this file to get channel ids using the pyyaml library, which was imported in this pr (see pyproject.toml).

### CODE REVIEW

**Review by hypergamer80 — COMMENTED** [review]
looks really nice! config.yml again is sooooo p e r f e c t

i have no knowledge of the other two files, and thus cannot approve nor request changes.

**Comment by dawnofmidnight** [comment]
> i have no knowledge of the other two files, and thus cannot approve nor request changes.

Those are just the config files for poetry. If you take a look at `pyproject.toml`, you'll see that `pyyaml` was added as a dependency. The other is a file that does things for poetry behind the scenes that none of us need to care about.

**Review by hypergamer80 — APPROVED** [review]
then i guess i'll approve.

**Comment by dannynotsmart** [comment]
i liek this too, should i approve

**Review by dannynotsmart — APPROVED** [review]
everything looks neat, organized, and accurate

**Review by Kronifer — APPROVED** [review]
LGTM, will merge. Next step is to parse the yaml

**Comment by dawnofmidnight** [comment]
Parsing can be done manually in the commands.

**Pull request merged**
