### PR TITLE
Added `--duck` command

### PR DESCRIPTION
**Pull request by Kronifer**
Closes https://github.com/cat-dev-group/bot/pull/38

Added a `--duck` command that generates and sends a random duck from quackstack. Fixed things with black, and renamed bans.py to moderation.py

### CODE REVIEW

**Review by Objectivitix — APPROVED** [review]
everything looks poggers, aiohttp coming in clutch again-

**Comment by Kronifer** [comment]
Lmao

**Comment by dannynotsmart** [comment]
checkin

**Review by dannynotsmart — APPROVED** [review]
looks about right
cant believe its not cat 😢 but whatever

**Pull request merged**
