### PR TITLE
Create zencat.py

### PR DESCRIPTION
**Pull request by Objectivitix**
<3 zen of pycat <3

### CODE REVIEW

**Review by Kronifer — APPROVED** [review]
Saw tested, lint passed so lgtm

**Review by ShakyaMajumdar — COMMENTED** [review]
LGTM but I'm not sure if we should have error handling here

Once we have a proper error handler, we can just raise a BadArgument in this file

**Comment by Objectivitix** [comment]
just leave it here for now. placeholders ;)

**Review by ShakyaMajumdar — APPROVED** [review]

**Comment by Objectivitix** [comment]
mmmmmmmmmmmmmerged

**Pull request merged**
